# coding: utf-8

"""
    WEM

    WEM Application API Documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.metas_api import MetasApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMetasApi(unittest.TestCase):
    """MetasApi unit test stubs"""

    def setUp(self):
        self.api = MetasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_goalsDeleteAll(self):
        """Test case for goalsDeleteAll

        Remover metas  # noqa: E501
        """
        pass

    def test_goalsPut(self):
        """Test case for goalsPut

        Editar metas  # noqa: E501
        """
        pass

    def test_goalsGet(self):
        """Test case for goalsGet

        Buscar metas  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
