# coding: utf-8

"""
    WEM

    WEM Application API Documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.apontamentos_api import ApontamentosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApontamentosApi(unittest.TestCase):
    """ApontamentosApi unit test stubs"""

    def setUp(self):
        self.api = ApontamentosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_appointmentDelete(self):
        """Test case for appointmentDelete

        Deletar apontamento  # noqa: E501
        """
        pass

    def test_appointmentPatch(self):
        """Test case for appointmentPatch

        Editar apontamento  # noqa: E501
        """
        pass

    def test_appointmentPost(self):
        """Test case for appointmentPost

        Criar apontamento  # noqa: E501
        """
        pass

    def test_appointmentQuery(self):
        """Test case for appointmentQuery

        Buscar apontamentos  # noqa: E501
        """
        pass

    def test_exchange_api_v2_appointment_status_appointment_id_patch(self):
        """Test case for exchange_api_v2_appointment_status_appointment_id_patch

        Aprovar apontamento  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
