# coding: utf-8

"""
    WEM

    WEM Application API Documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.relatrio_api import RelatrioApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRelatrioApi(unittest.TestCase):
    """RelatrioApi unit test stubs"""

    def setUp(self):
        self.api = RelatrioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reportCardsGet(self):
        """Test case for reportCardsGet

        Cards  # noqa: E501
        """
        pass

    def test_reportChartsGet(self):
        """Test case for reportChartsGet

        Chart  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
