# coding: utf-8

"""
    WEM

    WEM Application API Documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.converso_de_fatores_de_emisso_api import ConversoDeFatoresDeEmissoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConversoDeFatoresDeEmissoApi(unittest.TestCase):
    """ConversoDeFatoresDeEmissoApi unit test stubs"""

    def setUp(self):
        self.api = ConversoDeFatoresDeEmissoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_emissionsConversionFactorPatch(self):
        """Test case for emissionsConversionFactorPatch

        Editar fatores de emissão  # noqa: E501
        """
        pass

    def test_emissionsConversionFactorDeleteAll(self):
        """Test case for emissionsConversionFactorDeleteAll

        Remover todos os fatores  # noqa: E501
        """
        pass

    def test_emissionsConversionFactorGet(self):
        """Test case for emissionsConversionFactorGet

        Buscar fatores de emissão  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
